# Generated by Django 4.2.16 on 2024-10-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0007_cart_alter_pet_price_alter_pet_vaccination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('Total', models.FloatField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Status', models.CharField(max_length=30)),
                ('BOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.bookingtable')),
                ('PET', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.pet')),
            ],
        ),
    ]
