# Generated by Django 4.2.16 on 2024-10-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0008_bookingtable_bookingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.bookingdetails')),
                ('BOY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
