# Generated by Django 4.2.16 on 2024-10-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0009_assigntable'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntable',
            name='Comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
